[2024-04-19T04:23:29.038+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T04:23:29.078+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-19T04:23:08.742527+00:00 [queued]>
[2024-04-19T04:23:29.092+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-19T04:23:08.742527+00:00 [queued]>
[2024-04-19T04:23:29.094+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-19T04:23:29.121+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-04-19 04:23:08.742527+00:00
[2024-04-19T04:23:29.146+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=628) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T04:23:29.148+0000] {standard_task_runner.py:63} INFO - Started process 630 to run task
[2024-04-19T04:23:29.148+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-04-19T04:23:08.742527+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp_ecs1o83']
[2024-04-19T04:23:29.151+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask extract_data_from_wikipedia
[2024-04-19T04:23:29.247+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-19T04:23:08.742527+00:00 [running]> on host f76c4ac7736d
[2024-04-19T04:23:29.375+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T04:23:08.742527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T04:23:08.742527+00:00'
[2024-04-19T04:23:29.379+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T04:23:29.381+0000] {logging_mixin.py:188} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-04-19T04:23:32.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T04:23:32.514+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 50, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 27, in get_wikipedia_data
    table = soup.find_all("table", {"class": "wikitable sortable"})[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-04-19T04:23:32.570+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20240419T042308, start_date=20240419T042329, end_date=20240419T042332
[2024-04-19T04:23:32.604+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 104 for task extract_data_from_wikipedia (list index out of range; 630)
[2024-04-19T04:23:32.666+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-19T04:23:32.723+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-19T04:23:32.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
