[2024-04-28T15:30:20.192+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: example_local_kubernetes_executor.task_with_local_executor manual__2024-04-28T15:28:24.178016+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
