[2024-04-29T05:50:44.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T05:50:44.291+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T05:50:31.174480+00:00 [queued]>
[2024-04-29T05:50:44.300+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T05:50:31.174480+00:00 [queued]>
[2024-04-29T05:50:44.301+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T05:50:44.320+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-04-29 05:50:31.174480+00:00
[2024-04-29T05:50:44.330+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T05:50:44.332+0000] {standard_task_runner.py:63} INFO - Started process 119 to run task
[2024-04-29T05:50:44.333+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-04-29T05:50:31.174480+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpanee0fl4']
[2024-04-29T05:50:44.337+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask extract_data_from_wikipedia
[2024-04-29T05:50:44.395+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T05:50:31.174480+00:00 [running]> on host 349f346725e4
[2024-04-29T05:50:44.505+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T05:50:31.174480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T05:50:31.174480+00:00'
[2024-04-29T05:50:44.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T05:50:44.510+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T05:50:44.510+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/wikipedia_flow.py", line 33, in extract_wikipedia_data
    import geopy
ModuleNotFoundError: No module named 'geopy'
[2024-04-29T05:50:44.530+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20240429T055031, start_date=20240429T055044, end_date=20240429T055044
[2024-04-29T05:50:44.557+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task extract_data_from_wikipedia (No module named 'geopy'; 119)
[2024-04-29T05:50:44.588+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T05:50:44.619+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T05:50:44.622+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
