[2024-05-17T03:50:43.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T03:50:43.756+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T03:50:06.309653+00:00 [queued]>
[2024-05-17T03:50:43.810+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T03:50:06.309653+00:00 [queued]>
[2024-05-17T03:50:43.811+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-17T03:50:43.916+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data_ep1> on 2024-05-17 03:50:06.309653+00:00
[2024-05-17T03:50:43.984+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data_ep1', 'manual__2024-05-17T03:50:06.309653+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp172k28nq']
[2024-05-17T03:50:43.978+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2293) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T03:50:43.996+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask transform_wikipedia_data_ep1
[2024-05-17T03:50:43.997+0000] {standard_task_runner.py:63} INFO - Started process 2302 to run task
[2024-05-17T03:50:44.373+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T03:50:06.309653+00:00 [running]> on host 85d72ecba59d
[2024-05-17T03:50:44.722+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data_ep1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T03:50:06.309653+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T03:50:06.309653+00:00'
[2024-05-17T03:50:44.727+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T03:52:33.764+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1
[2024-05-17T03:55:49.962+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Workers%27+Stadium%2C+China&format=json&limit=1
[2024-05-17T03:57:08.137+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Est%C3%A1dio+Governador+Magalh%C3%A3es+Pinto%2C+Brazil&format=json&limit=1
[2024-05-17T04:01:20.834+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=BORUSSIA-PARK%2C+Germany&format=json&limit=1
[2024-05-17T04:01:55.313+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=San+Mam%C3%A9s%2C+Spain&format=json&limit=1
[2024-05-17T04:03:04.793+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Stadion+Feijenoord%2C+Netherlands&format=json&limit=1
[2024-05-17T04:03:58.110+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Est%C3%A1dio+Jos%C3%A9+Alvalade%2C+Portugal&format=json&limit=1
[2024-05-17T04:05:53.765+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Miyagi+Stadium%2C+Japan&format=json&limit=1
[2024-05-17T04:09:11.577+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Estadio+Pedro+Bidegain%2C+Argentina&format=json&limit=1
[2024-05-17T04:09:29.183+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Estadio+Universidad+San+Marcos%2C+Peru&format=json&limit=1
[2024-05-17T04:12:00.442+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Baba+Yara+Stadium%2C+Ghana&format=json&limit=1
[2024-05-17T04:12:48.733+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Estadio+Campe%C3%B3n+del+Siglo%2C+Uruguay&format=json&limit=1
[2024-05-17T04:13:11.958+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Stade+Ahmed-Zabana%2C+Algeria&format=json&limit=1
[2024-05-17T04:16:06.604+0000] {warnings.py:110} WARNING - /opt/***/pipelines/wikipedia_pipeline.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates['location'] = duplicates.apply(lambda x: get_lat_long(x['country'], x['city']), axis=1)

[2024-05-17T04:16:06.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T04:16:06.741+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 119, in transform_wikipedia_data_ep1
    longtitude.append(tam[i].split(',')[0].split('(')[1])
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-05-17T04:16:07.032+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data_ep1, execution_date=20240517T035006, start_date=20240517T035043, end_date=20240517T041606
[2024-05-17T04:16:07.499+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task transform_wikipedia_data_ep1 (list index out of range; 2302)
[2024-05-17T04:16:07.798+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T04:16:08.501+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T04:16:08.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
