[2024-05-17T06:04:28.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T06:04:28.952+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T06:03:55.744070+00:00 [queued]>
[2024-05-17T06:04:28.973+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T06:03:55.744070+00:00 [queued]>
[2024-05-17T06:04:28.974+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-17T06:04:29.005+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data_ep1> on 2024-05-17 06:03:55.744070+00:00
[2024-05-17T06:04:29.015+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T06:04:29.020+0000] {standard_task_runner.py:63} INFO - Started process 3482 to run task
[2024-05-17T06:04:29.020+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data_ep1', 'manual__2024-05-17T06:03:55.744070+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpt7vo_ijb']
[2024-05-17T06:04:29.022+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask transform_wikipedia_data_ep1
[2024-05-17T06:04:29.093+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T06:03:55.744070+00:00 [running]> on host 85d72ecba59d
[2024-05-17T06:04:29.229+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data_ep1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T06:03:55.744070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T06:03:55.744070+00:00'
[2024-05-17T06:04:29.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T06:05:15.229+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1
[2024-05-17T06:06:14.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T06:06:14.819+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 94, in transform_wikipedia_data_ep1
    stadiums_df['latitude'] = stadiums_df.apply(lambda x: get_lat_long(x['country'], x['stadium'])[0], axis=1)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 94, in <lambda>
    stadiums_df['latitude'] = stadiums_df.apply(lambda x: get_lat_long(x['country'], x['stadium'])[0], axis=1)
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2024-05-17T06:06:14.846+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data_ep1, execution_date=20240517T060355, start_date=20240517T060428, end_date=20240517T060614
[2024-05-17T06:06:14.874+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task transform_wikipedia_data_ep1 ('NoneType' object is not subscriptable; 3482)
[2024-05-17T06:06:14.925+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T06:06:14.989+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T06:06:15.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
