[2024-05-16T17:10:44.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T17:10:44.854+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-16T16:55:45.324276+00:00 [queued]>
[2024-05-16T17:10:44.921+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-16T16:55:45.324276+00:00 [queued]>
[2024-05-16T17:10:44.929+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-16T17:10:45.045+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-05-16 16:55:45.324276+00:00
[2024-05-16T17:10:45.099+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2011) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T17:10:45.118+0000] {standard_task_runner.py:63} INFO - Started process 2013 to run task
[2024-05-16T17:10:45.106+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-05-16T16:55:45.324276+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpypqnoift']
[2024-05-16T17:10:45.130+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask write_wikipedia_data
[2024-05-16T17:10:45.322+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-16T16:55:45.324276+00:00 [running]> on host 85d72ecba59d
[2024-05-16T17:10:45.699+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T16:55:45.324276+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T16:55:45.324276+00:00'
[2024-05-16T17:10:45.701+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T17:10:45.895+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T17:10:45.897+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 131, in write_wikipedia_data
    load_to_db(data, table_name, sql_connection)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 112, in load_to_db
    df.to_sql(table_name, sql_connection, if_exist='replace', index = False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame.to_sql() got an unexpected keyword argument 'if_exist'
[2024-05-16T17:10:45.937+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, execution_date=20240516T165545, start_date=20240516T171044, end_date=20240516T171045
[2024-05-16T17:10:45.983+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task write_wikipedia_data (NDFrame.to_sql() got an unexpected keyword argument 'if_exist'; 2013)
[2024-05-16T17:10:46.035+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T17:10:46.080+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T17:10:46.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
